# ci-pipeline.yaml
project: protein-interaction-coevolution

steps:
  find_homologues:
    script: scripts/blast_and_pair.py
    inputs:
      - inputs/find_homologues/${project}/queryA.fasta
      - inputs/find_homologues/${project}/queryB.fasta
    outputs:
      - results/find_homologues/${project}/paired_sequences.json
    params:
      n_hits: 5000
      email: "mp957@cam.ac.uk"

  build_msas:
    script: scripts/build_msas.sh
    inputs:
      - results/find_homologues/${project}/paired_sequences.json
    outputs:
      - results/msas/${project}/proteinA.aln
      - results/msas/${project}/proteinB.aln
      - results/msas/${project}/proteinAB.aln

  coevolution_analysis:
    script: scripts/coevolution_analysis.py
    inputs:
      - results/msas/${project}/proteinAB.aln
    outputs:
      - results/coevolution/${project}/coevolution_results.couplings

  generate_heatmaps:
    script: scripts/generate_heatmaps.py
    inputs:
      - results/find_homologues/${project}/paired_sequences.json
      - results/msas/${project}/proteinAB.aln
      - results/coevolution/${project}/coevolution_results.couplings
    outputs:
      - results/heatmaps/${project}/couplings_mapped.csv
      - results/heatmaps/${project}/global_heatmap.png
      - results/heatmaps/${project}/network_top95.png
      - results/heatmaps/${project}/network_top98.png
